#!/usr/bin/env bash

set -e

if [[ $1 == "--help" || $1 == "-h" ]]; then
    echo "Usage:"
    echo "./manage-cdp approve <WETH/DAI>"
    echo "./manage-cdp lock-draw CDP_ID ETH_AMOUNT DAI_AMOUNT"
    echo "./manage-cdp draw CDP_ID DAI_AMOUNT"
    echo "./manage-cdp wipe-all CDP_ID"
    echo "./manage-cdp wipe-all-free CDP_ID ETH_AMOUNT"
else
    [[ "$ETH_RPC_URL" && "$(seth chain)" == "ethlive"  ]] || { echo "Please set a mainnet ETH_RPC_URL"; exit 1;  }

    [[ "$ETH_FROM" ]] || { echo "Please set a ETH_FROM"; exit 1;  }

    export CDP_MANAGER=0x5ef30b9986345249bc32d8928B7ee64DE9435E39
    export PROXY_ACTIONS=0x82ecD135Dce65Fbc6DbdD0e4237E0AF93FFD5038
    export MCD_JUG=0x19c0976f590D67707E62397C87829d896Dc0f1F1
    export MCD_JOIN_ETH_A=0x2F0b23f53734252Bda2277357e97e1517d6B042A
    export MCD_JOIN_DAI=0x9759A6Ac90977b93B58547b4A71c78317f391A28
    export ETH=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
    export MCD_DAI=0x6B175474E89094C44Da98b954EedeAC495271d0F
    export PROXY_REGISTRY=0x4678f0a6958e4D2Bc4F1BAF7Bc52E8F3564f3fE4

    export MY_PROXY
    export ETH_AMOUNT
    export DAI_AMOUNT
    export calldata

    MY_PROXY=$(seth call "$PROXY_REGISTRY" 'proxies(address)(address)' "$ETH_FROM")

    [[ "$MY_PROXY" != "0x0000000000000000000000000000000000000000" ]] || { echo "Not existing proxy"; exit 1;  }

    [[ $(seth call "$MY_PROXY" 'owner()(address)') == "$ETH_FROM" ]] || { echo "Owner doesn't match"; exit 1;  }

    [[ $(seth call "$MY_PROXY" 'authority()(address)') == "0x0000000000000000000000000000000000000000" ]] || { echo "!!!!!!Warning: Proxy has an authority!!!!!"; }

    if [[ $1 == "approve" ]]; then
        if [[ $2 == "DAI" ]]; then
            # APPROVE DAI
            echo "Approving DAI to proxy: $MY_PROXY..."
            seth send "$MCD_DAI" 'approve(address,uint256)' "$MY_PROXY" "$(seth --to-int256 "-1")"
        fi

        if [[ $2 == "WETH" ]]; then
            # APPROVE WETH
            echo "Approving WETH to proxy: $MY_PROXY..."
            seth send "$ETH" 'approve(address,uint256)' "$MY_PROXY" "$(seth --to-int256 "-1")"
        fi
    else
        if [[ $1 == "lock-draw" ]]; then
            # LOCK AND DRAW
            MY_CDP="$2"
            ETH_AMOUNT="$(seth --to-wei "$3" "eth")"
            DAI_AMOUNT="$(seth --to-wei "$4" "eth")"
            echo "CDP $MY_CDP: Lock $3 WETH and Draw $4 DAI"
            calldata="$(seth calldata 'lockGemAndDraw(address,address,address,address,uint256,uint256,uint256,bool)' "$CDP_MANAGER" "$MCD_JUG" "$MCD_JOIN_ETH_A" "$MCD_JOIN_DAI" "$MY_CDP" "$ETH_AMOUNT" "$DAI_AMOUNT" 1)"
        elif [[ $1 == "draw" ]]; then
            # DRAW
            MY_CDP="$2"
            DAI_AMOUNT="$(seth --to-wei "$3" "eth")"
            echo "CDP $MY_CDP: Draw $3 DAI"
            calldata="$(seth calldata 'draw(address,address,address,uint256,uint256)' "$CDP_MANAGER" "$MCD_JUG" "$MCD_JOIN_DAI" "$MY_CDP" "$DAI_AMOUNT")"
        elif [[ $1 == "wipe-all" ]]; then
            # WIPE ALL
            MY_CDP="$2"
            echo "CDP $MY_CDP: Wipe all DAI"
            calldata="$(seth calldata 'safeWipeAll(address,address,uint256,address)' "$CDP_MANAGER" "$MCD_JOIN_DAI" "$MY_CDP" "$MY_PROXY")"
        elif [[ $1 == "wipe-all-free" ]]; then
            # WIPE ALL AND FREE
            MY_CDP="$2"
            ETH_AMOUNT="$(seth --to-wei "$3" "eth")"
            echo "CDP $MY_CDP: Wipe all DAI and free $3 WETH"
            calldata="$(seth calldata 'wipeAllAndFreeGem(address,address,address,uint256,uint256)' "$CDP_MANAGER" "$MCD_JOIN_ETH_A" "$MCD_JOIN_DAI" "$MY_CDP" "$ETH_AMOUNT")"
        else
            echo "Wrong command"
            exit 1
        fi

        # EXECUTE
        seth send "$MY_PROXY" 'execute(address,bytes)' "$PROXY_ACTIONS" "$calldata"
    fi
fi
